theme = "blowfish"
baseURL = "https://pistaha.github.io/my-portfolio/"
defaultContentLanguage = "ru"
enableRobotsTXT = true
summaryLength = 0
buildFuture = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
