colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = false

mainSections = ["portfolio"]

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = false
  showRecentItems = 5
  showMoreLink = false
  cardView = false
  cardViewScreenWidth = false

[article]
  showDate = false
  showAuthor = true
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = false
  showWordCount = false

[list]
  showSummary = false
  showTableOfContents = false
  showCards = false
  groupByYear = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]
